feat: Exit Button
ether/etherpad-lite pull request #6763
Opened 2024-11-16 10:41 UTC by Unanemouslyanonymous

This feature adds an exit Button to the top right of the toolbar, making it easy for the user to nav back to the home, initially the user had to edit the browser endpoints inorder to moveback to the home page. now with the exit button it is pretty much a click away!
This is my first OSS contribution, changes are welcome

![Uploading image.png…]()

2024-11-16 10:42 UTC, Unanemouslyanonymous commented
![Screenshot 2024-11-16 104001](https://github.com/user-attachments/assets/2cb9548b-01dd-454a-a406-0766fea52498)

2025-03-31 19:05 UTC, SamTV12345 commented on src/static/js/pad_editbar.ts
> +      console.log('Exit button clicked');
Maybe remove this console.log statement

2025-03-31 19:05 UTC, SamTV12345 requested changes

2025-03-31 19:05 UTC, SamTV12345 commented on src/static/js/pad_editbar.ts
> +      window.location.href = '/';
Also relative url is important for this to work

2025-08-01 20:40 UTC, closed without merging